config/routes.rb
Rails.application.routes.draw do

  resources :itemimages do
	  collection do
		  post :sort
		end
	end
  resources :permcls
  resources :permcl_actions
  resources :permissions do
		collection do
			post :user_permissions
		end
  end
  get 'password_resets/new'

  get 'signup', to: 'users#newuser', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :password_resets
  resources :sessions
  resources :users
  resources :homes
  resources :items do
  	collection do
  		get  :scanner
  		post :get_barcode
  		get  :multi_barcode_pdf
  		post :delete_selected
  		match 'search' => 'items#search', via: [:get, :post], as: :search
  	end
  end

  root "homes#index"

end

app/models/itemimage.rb
class Itemimage < ActiveRecord::Base

  acts_as_list
	belongs_to :item

	has_attached_file :image, styles: { medium: "600x600>", thumb: "100x100>" },
    :path => ":rails_root/public/system/images/itemimages/:id/:style/:basename.:extension",
    :url  => "/system/images/itemimages/:id/:style/:basename.:extension"

	validates_attachment :image,
                     content_type: { content_type: /\Aimage\/.*\z/ },
                     size: { less_than: 5.megabyte }


end

app/controllers/itemimages_controller.rb
class ItemimagesController < ApplicationController
  load_and_authorize_resource
  before_action :set_itemimage, only: [:show, :edit, :update, :destroy]

  # GET /itemimages
  # GET /itemimages.json
  def index
    @itemimages = Itemimage.all
  end

  # GET /itemimages/1
  # GET /itemimages/1.json
  def show
  end

  # GET /itemimages/new
  def new
    @itemimage = Itemimage.new
  end

  # GET /itemimages/1/edit
  def edit
  end

  # POST /itemimages
  # POST /itemimages.json
  def create
    @itemimage = Itemimage.create(itemimage_params) #загружаем картинки через форму загрузки js файл -  create.js
#     @itemimage = Itemimage.new(itemimage_params)
#     respond_to do |format|
#       if @itemimage.save
#         format.html { redirect_to @itemimage, notice: 'Itemimage was successfully created.' }
#         format.json { render :show, status: :created, location: @itemimage }
#       else
#         format.html { render :new }
#         format.json { render json: @itemimage.errors, status: :unprocessable_entity }
#       end
#     end
  end

  # PATCH/PUT /itemimages/1
  # PATCH/PUT /itemimages/1.json
  def update
    respond_to do |format|
      if @itemimage.update(itemimage_params)
        format.html { redirect_to @itemimage, notice: 'Itemimage was successfully updated.' }
        format.json { render :show, status: :ok, location: @itemimage }
      else
        format.html { render :edit }
        format.json { render json: @itemimage.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /itemimages/1
  # DELETE /itemimages/1.json
  def destroy
    @itemimage.destroy
    flash[:info] = "Картинка удалена"
    if params[:from] == 'items'
	    redirect_to :back
	    else
	    respond_to do |format|
	      format.html { redirect_to itemimages_url, notice: 'Картинка удалена' }
	      format.json { head :no_content }
        format.js
	    end
    end
  end

  def sort
	  params[:itemimage].each_with_index do |id, index|
    Itemimage.where( id: id).update_all(position: index+1)
  	end
	render nothing: true
	head :ok
	end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_itemimage
      @itemimage = Itemimage.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def itemimage_params
      params.require(:itemimage).permit(:item_id, :image, :position, :item_new)
    end
end

app/helpers/itemimages_helper.rb
module ItemimagesHelper
end

app/views/itemimages/_form.html.erb
<%= simple_form_for(@itemimage) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :item_id %>
    <%= f.input :image %>
    <%= f.input :position %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/itemimages/_picview.html.erb
<% if itemimage.persisted?%>
<%= content_tag_for :li, itemimage do %>
<span class="sort-image">
<%= link_to image_tag(itemimage.image.url(:thumb) , :class => "sort-image-a-img", "data-content"=>"#{image_tag(itemimage.image.url(:medium))}", "data-delay"=>"{'show':200,'hide':200}", "data-html"=>"true", "data-placement"=>"left", "data-toggle"=>"popover", "data-trigger"=>"hover"), itemimage.image.url, :target => '_blank', :class => "sort-image-a"  %>
  <div class="actions">
    <% if itemimage.item_id == nil || ''%>
    <span class="pseudoDelete" onclick="pseudoDelete(<%= itemimage.id %>)" id="<%= itemimage.id %>"><i class="fa fa-trash fa-2x" aria-hidden="true"></i></span>
<% else %>
<%= link_to '<i class="fa fa-trash fa-2x" aria-hidden="true"></i>'.html_safe, itemimage_path(itemimage, :from=>"items"), :confirm => 'Точно удалить?', :method => :delete %>
<% end %>
  </div>
  </span>
<%end%>
<%end%>

app/views/itemimages/create.js.erb
<% if @itemimage.new_record? %>
  alert("Failed to upload image: <%= j @itemimage.errors.full_messages.join(', ').html_safe %>");
<% else %>
  $('#images').append("<%=j render partial: 'picview', locals: { itemimage: @itemimage } %>");
<% end %>

app/views/itemimages/edit.html.erb
<h1>Editing Itemimage</h1>

<%= render 'form' %>

<%= link_to 'Show', @itemimage %> |
<%= link_to 'Back', itemimages_path %>

app/views/itemimages/index.html.erb
<h1>Listing Itemimages</h1>

<table>
  <thead>
    <tr>
      <th>Item</th>
      <th>Item_new</th>
      <th>Image Url</th>
      <th>Position</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @itemimages.each do |itemimage| %>
      <tr>
        <td><%= itemimage.item_id %></td>
        <td><%= truncate(itemimage.item_new, :length => 20) %></td>
        <td><%= truncate(itemimage.image.to_s, :length => 20)%></td>
        <td><%= itemimage.position %></td>
        <td><%= link_to(image_tag(itemimage.image.url(:thumb)), itemimage.image.url, target: '_blank') if itemimage.image.exists? %></td>
        <td><%= link_to 'Show', itemimage %></td>
        <td><%= link_to 'Edit', edit_itemimage_path(itemimage) %></td>
        <td><%= link_to 'Destroy', itemimage, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Itemimage', new_itemimage_path %>

app/views/itemimages/new.html.erb
<h1>New Itemimage</h1>

<%= render 'form' %>

<%= link_to 'Back', itemimages_path %>

app/views/itemimages/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Item:</strong>
  <%= @itemimage.item_id %>
</p>

<p>
  <strong>Image:</strong>
  <%= @itemimage.image %>
</p>

<p>
  <strong>Position:</strong>
  <%= @itemimage.position %>
</p>

<%= link_to 'Edit', edit_itemimage_path(@itemimage) %> |
<%= link_to 'Back', itemimages_path %>