config/routes.rb
Rails.application.routes.draw do

  resources :itemimages do
	  collection do
		  post :sort
		end
	end
  resources :permcls
  resources :permcl_actions
  resources :permissions do
		collection do
			post :user_permissions
		end
  end
  get 'password_resets/new'

  get 'signup', to: 'users#newuser', as: 'signup'
  get 'login', to: 'sessions#new', as: 'login'
  get 'logout', to: 'sessions#destroy', as: 'logout'

  resources :password_resets
  resources :sessions
  resources :users
  resources :homes
  resources :items do
  	collection do
  		get  :scanner
  		post :get_barcode
  		get  :multi_barcode_pdf
  		post :delete_selected
  		match 'search' => 'items#search', via: [:get, :post], as: :search
  	end
  end

  root "homes#index"

end

app/models/item.rb
class Item < ActiveRecord::Base
  belongs_to :user
  has_many	 :itemimages, :dependent => :destroy
  accepts_nested_attributes_for :itemimages, allow_destroy: true

  validates :sku, presence: true, uniqueness: true
  validates :title, presence: true

end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  load_and_authorize_resource
  before_action :set_item, only: [:show, :edit, :update, :destroy]
  # before_filter :authorize, only: [:edit, :update]

  # GET /items
  # GET /items.json
  def index
    @items = Item.all
  end

  # GET /items/1
  # GET /items/1.json
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
    @itemimages = @item.itemimages.present? ? @item.itemimages : @item.itemimages.build
  end

  # GET /items/1/edit
  def edit
    @itemimages = @item.itemimages.present? ? @item.itemimages : @item.itemimages.build
  end

  # POST /items
  # POST /items.json
  def create
    @item = Item.new(item_params)

    respond_to do |format|
      if @item.save
          images = Itemimage.where(:item_new => params[:authenticity_token])
          images.each do |image|
            image.update_attributes(item_id: @item.id)
          end

        format.html { redirect_to @item, notice: 'Item was successfully created.' }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1
  # PATCH/PUT /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        if params[:images]
        params[:images].each do |image|
          @item.itemimages.create(image: image)
        end
      end
        format.html { redirect_to @item, notice: 'Item was successfully updated.' }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1
  # DELETE /items/1.json
  def destroy
    @item.destroy
    respond_to do |format|
      format.html { redirect_to items_url, notice: 'Item was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def item_params
      params.require(:item).permit(:sku, :barcode, :title, :description, :quantity, :costprice, :price, :user_id, :image_file_name, :itemimages_attributes =>[:id, :item_id, :_destroy, image: []])
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="row">
<div class="col-6 ">
<%= simple_form_for @item, :html => { multipart: true } do |f| %>
<%= f.error_notification %>
    <%= f.input :user_id , as: :hidden, :input_html => { :value => current_user.id }%>
    <%= f.input :sku , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }%>
    <%= f.input :barcode , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }%>
    <%= f.input :title , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }%>
    <%= f.input :description , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group' }%>
    <div class="row">
    <%= f.input :quantity , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group  col-4' }%>
    <%= f.input :costprice , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group col-4' }%>
    <%= f.input :price , input_html: { class: 'form-control' }, wrapper_html: { class: 'form-group col-4' }%>
    </div>
  <div class="btn-group my-3" role="group">
    <%= f.button :submit, 'Сохранить' , class: 'btn btn-success'%>
    <%= link_to 'Назад', items_path, class: 'btn btn-info' %>
    </div>
</div>

<% end %>

<div class="col-6">
    <%= form_for Itemimage.new, :url => itemimages_path, html: { multipart: true } do |f| %>
    <% if @item.new_record? %>
    <script type="text/javascript">
      $(document).ready(function() {
      var val = $( "input[name*='authenticity_token']" ).val( );
      $( "#itemimage_item_id" ).val(val);
      });
    </script>
    <input type="hidden" name="itemimage[item_new]" id="itemimage_item_id" value="">
    <% else %>
      <%= f.hidden_field :item_id, value: @item.id %>
    <% end %>
    <%= f.file_field :image, multiple: true , name: 'itemimage[image]', class: "inputfile"  %>
      <%= f.label :image do %>
        <i class="fa fa-cloud-upload fa-2x" aria-hidden="true"></i>
        <span class="uploadtext">Upload</span>
      <% end %>
    <% end%>
  <% # jquery upload template # %>
  <script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>

  <ul id="images" data-update-url="<%= sort_itemimages_url %>">
    <%@item.itemimages.each do |pic|%>
      <% if pic.persisted?%>
    <%= content_tag_for :li, pic do %>
    <span class="sort-image">
      <%= link_to image_tag(pic.image.url(:thumb) , "data-content"=>"#{image_tag(pic.image.url(:medium))}", "data-delay"=>"{'show':200,'hide':200}", "data-html"=>"true", "data-placement"=>"left", "data-toggle"=>"popover", "data-trigger"=>"hover"), pic.image.url, :target => '_blank', :class => "sort-image-a" %>
      <div class="actions">
        <%= link_to '<i class="fa fa-trash fa-2x" aria-hidden="true"></i>'.html_safe, itemimage_path(pic, :from=>"items"), :confirm => 'Точно удалить?', :method => :delete %>
      </div>
      </span>
    <%end%>
    <%end%>
    <%end%>
  </ul>
</div>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form' %>

app/views/items/index.html.erb
<h1>Товары</h1>
<p><%= link_to 'Добавить', new_item_path %></p>
<div class="table-responsive">
<table class="table table-hover table-condensed table-sm">
  <thead>
    <tr class="bg-light">
      <th>Sku</th>
      <th>Barcode</th>
      <th>Title</th>
      <th>Description</th>
      <th>Quantity</th>
      <th>Costprice</th>
      <th>Price</th>
      <th colspan="2"></th>
    </tr>
  </thead>

  <tbody>
    <% @items.each do |item| %>
      <tr>
        <td><%= link_to item.sku , item %></td>
        <td><%= item.barcode %></td>
        <td><%= item.title %></td>
        <td><%= item.description %></td>
        <td><%= item.quantity %></td>
        <td><%= item.costprice %></td>
        <td><%= item.price %></td>
        <td><%= link_to '<i class="fa fa-pencil" aria-hidden="true"></i>'.html_safe, edit_item_path(item) %></td>
        <td><%= link_to '<i class="fa fa-trash" aria-hidden="true"></i>'.html_safe, item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form' %>

app/views/items/show.html.erb
<div class="row">
<div class="col-5">
<p>
  <strong>Sku:</strong>
  <%= @item.sku %>
</p>

<p>
  <strong>Barcode:</strong>
  <%= @item.barcode %>
</p>

<p>
  <strong>Title:</strong>
  <%= @item.title %>
</p>

<p>
  <strong>Description:</strong>
  <%= @item.description %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @item.quantity %>
</p>

<p>
  <strong>Costprice:</strong>
  <%= @item.costprice %>
</p>

<p>
  <strong>Price:</strong>
  <%= @item.price %>
</p>

<p>
  <strong>User:</strong>
  <%= @item.user.email %>
</p>

<div class="col-6 btn-group my-3" role="group">
  <%= link_to 'Edit', edit_item_path(@item), class: 'btn btn-success' %>
  <%= link_to 'Назад', items_path, class: 'btn btn-info' %>
</div>
</div>
<div class="col-md-7 col-xs-12">
    <%= form_for Itemimage.new, :url => itemimages_path, html: { multipart: true } do |f| %>
    <%= f.hidden_field :item_id, value: @item.id %>
    <%= f.file_field :image, multiple: true , name: 'itemimage[image]', class: "inputfile"  %>
      <%= f.label :image do %>
        <i class="fa fa-cloud-upload fa-2x" aria-hidden="true"></i>
        <span class="uploadtext">Upload</span>
      <% end %>
    <% end%>
  <% # jquery upload template # %>
  <script id="template-upload" type="text/x-tmpl"><div class="upload">{%=o.name%}<div class="progress"><div class="bar" style="width: 0%"></div></div></div></script>

  <ul id="images" data-update-url="<%= sort_itemimages_url %>">
    <%@item.itemimages.each do |pic|%>
      <% if pic.persisted?%>
    <%= content_tag_for :li, pic do %>
    <span class="sort-image">
      <%= link_to image_tag(pic.image.url(:thumb), "data-content"=>"#{image_tag(pic.image.url(:medium))}", "data-delay"=>"{'show':200,'hide':200}", "data-html"=>"true", "data-placement"=>"left", "data-toggle"=>"popover", "data-trigger"=>"hover"), pic.image.url, :target => '_blank', :class => "sort-image-a"  %>
      <div class="actions">
        <%= link_to '<i class="fa fa-trash fa-2x" aria-hidden="true"></i>'.html_safe, itemimage_path(pic, :from=>"items"), :confirm => 'Точно удалить?', :method => :delete %>
      </div>
      </span>
    <%end%>
    <%end%>
    <%end%>
  </ul>
</div>
</div>